// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/viictormg/clubHub/internal/domain/dto"
)

// ICompanyUsecase is an autogenerated mock type for the ICompanyUsecase type
type ICompanyUsecase struct {
	mock.Mock
}

// GetCompanyByNameUsecase provides a mock function with given fields: name
func (_m *ICompanyUsecase) GetCompanyByNameUsecase(name string) (*dto.ResponseCompanyByNameDTO, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyByNameUsecase")
	}

	var r0 *dto.ResponseCompanyByNameDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dto.ResponseCompanyByNameDTO, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *dto.ResponseCompanyByNameDTO); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseCompanyByNameDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICompanyUsecase creates a new instance of ICompanyUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICompanyUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICompanyUsecase {
	mock := &ICompanyUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
