// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/viictormg/clubHub/internal/domain/entity"
)

// IOwnerAdapter is an autogenerated mock type for the IOwnerAdapter type
type IOwnerAdapter struct {
	mock.Mock
}

// GetOwnerByCompanyIDAdapter provides a mock function with given fields: companyID
func (_m *IOwnerAdapter) GetOwnerByCompanyIDAdapter(companyID int) (*entity.OwnerEntity, error) {
	ret := _m.Called(companyID)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerByCompanyIDAdapter")
	}

	var r0 *entity.OwnerEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.OwnerEntity, error)); ok {
		return rf(companyID)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.OwnerEntity); ok {
		r0 = rf(companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OwnerEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOwnerAdapter creates a new instance of IOwnerAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOwnerAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOwnerAdapter {
	mock := &IOwnerAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
